#Write a program that receives a number and prints its multiplication table
i=int(input("please write a number: "))
print("1 x",i, '=' , 1 * i)
print("2 x",i, '=' , 2 * i)
print("3 x",i, '=' , 3 * i)
print("4 x",i, '=' , 4 * i)
print("5 x",i, '=' , 5 * i)
print("6 x",i, '=' , 6 * i)
print("7 x",i, '=' , 7 * i)
print("8 x",i, '=' , 8 * i)
print("9 x",i, '=' , 9 * i)
print("10 x",i, '=' , 10 * i)
